# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml#L32
seed: 42

n_timesteps: !!float 1e10
policy: 'MlpPolicy'
n_steps: 1024
batch_size: 1024
gae_lambda: 0.95
gamma: 0.99
n_epochs: 5
ent_coef: 0.01
# learning_rate: !!float 1e-4
clip_range: !!float 0.2
policy_kwargs: "dict(
                  activation_fn=nn.ELU,
                  net_arch=[64, 128,256,128,64],
                  squash_output=False,
                )"
vf_coef: 0.001
max_grad_norm: 1.0
device: "cuda:0"
